function getUrlParameter(name) {
  const urlParams = new URLSearchParams(window.location.search);
  return urlParams.get(name);
}
document.addEventListener("DOMContentLoaded", function () {
    console.log("Document loaded. Initializing test editor...");

    const type = getUrlParameter('type'); // 获取 URL 中的 type 参数

    const currentParams = window.location.search; // 获取当前 URL 参数部分（包括 ?）

    // Show or hide specific functions based on the type parameter
      if (type === 'a') {
        $('#suggestion').hide(); // hide suggestion
        $('#grammar').show();    // show grammar
        $('#tab').hide(); // hide suggestion
        $('#F1').show();    // show grammar
      } else if (type === 'b' || type === 'c' || type === 'd'|| type === 'f') {
        $('#suggestion').show(); // show suggestion
        $('#grammar').hide();    // hide grammar
         $('#F1').hide(); // hide suggestion
        $('#tab').show();    // show grammar
      } else if (type === 'e') {
        $('#shortcuts').hide();
      }


    // new Quill
    const quill = new Quill("#editor-container", {
        theme: "snow",
        placeholder: "Start writing here...",
        modules: {
          toolbar: false
        }
    });

    let aiRequested = false;  // Ensure that the user triggers the AI
    let aiAccepted = false;   // Ensure that the user selects the AI-generated text

    // hide "Test completed"
    document.getElementById("status-message").style.display = "none";
    document.getElementById("next-page-btn").style.display = "none";

    // Modelling AI-generated recommendations
    const fakeSuggestions = [
        "This is a test suggestion.",
        "Another possible completion.",
        "Try this sentence instead.",
    ];

    // Listening to Tab and F1 keys to simulate AI interactions
    document.addEventListener("keydown", function (event) {
        if (type === 'a' && event.key === "F1") {
            // Type A: Listening to F1
            event.preventDefault();
            if (!aiRequested) {
                aiRequested = true;
                showFakeSuggestions(true); // 传递 isGrammar=true
            }
        } else if (event.key === "Tab") {
            // other Type: Listening to Tab
            event.preventDefault();
            if (!aiRequested) {
                aiRequested = true;
                showFakeSuggestions(false); // 传递 isGrammar=false
            }
        }
    });

    // Displays the recommendations generated by the AI
    function showFakeSuggestions(isGrammar) {
        const overlay = document.getElementById("frontend-overlay");
        overlay.innerHTML = ""; // 清空现有内容
        overlay.classList.remove("hidden");

        // Generating recommendations
        const fakeSuggestions1 = [
            "The week is just getting started, and there’s a lot to do.",
            "I’m already looking forward to the weekend.",
            "Let’s make it a productive day!",
        ];
        const fakeSuggestions2 = [
            "Original: Today is Monday.",
            "Revised: It’s Monday today.",
        ];
        if (type === 'a') {
            fakeSuggestions2.forEach((suggestion, index) => {
                const item = document.createElement("div");
                item.classList.add("dropdown-item");
                item.textContent = suggestion;
                quill.deleteText(0, quill.getLength());
                suggestion = suggestion.replace(/^Revised:\s*/, '').replace(/^Original:\s*/, '');

                item.addEventListener("click", function () {
                    insertSuggestion(suggestion);
                });
                overlay.appendChild(item);
            });
        }
        else {
            fakeSuggestions1.forEach((suggestion, index) => {
                const item = document.createElement("div");
                item.classList.add("dropdown-item");
                item.textContent = suggestion;
                item.addEventListener("click", function () {
                    insertSuggestion(suggestion);
                });
                overlay.appendChild(item);
            });
        }


        // Calculate the correct display position
        positionDropdownMenu();
    }
    function positionDropdownMenu() {
        // Checking for recommendations
        if ($('#frontend-overlay').children().length === 0) {
            alert('No suggestions to be shown. Press tab key to get new suggestions!');
            return;
        }

        // Get Offset
        let offsetTop = $('#editor-view').offset().top;
        let offsetLeft = $('#editor-view').offset().left;
        let offsetBottom = $('footer').offset().top;

        let position = quill.getBounds(0);
        let top = offsetTop + position.top + 60 + 40;  // + Toolbar 高度 + 行高
        let left = offsetLeft + position.left;

        // 计算最大宽度和总高度
        let maxWidth = 0;
        let totalHeight = 0;
        $(".dropdown-item").each(function () {
            let width = $(this).outerWidth(true);
            let height = $(this).outerHeight(true);

            if (width > maxWidth) {
                maxWidth = width;
            }
            totalHeight += height;
        });

        let finalWidth = Math.min(maxWidth, $('#editor-view').outerWidth(true));
        let rightmost = left + maxWidth;
        let bottommost = top + totalHeight;

        let width_overflow = rightmost > $("#editor-view").width();

        // 如果超出右侧边界，调整左偏移量
        if (width_overflow) {
            left = offsetLeft + 30;  // 30px padding
        }

        // 计算是否需要向上移动
        const bodyHeight = $('body').outerHeight(true);
        let moveUpDropdown = false;

        if (bottommost >= ($("#editor-view").height() + 100)) {
            if (top > (bodyHeight / 2)) {
                moveUpDropdown = true;
            }
        }

        if (moveUpDropdown) {
            let maxHeight = top - 100;
            if (totalHeight > maxHeight) {
                totalHeight = maxHeight;
            }
            top = top - totalHeight - 60;
        } else {
            let maxHeight = $("#editor-view").height() - offsetTop - position.top + 60;
            if (maxHeight < 100) {
                maxHeight = 100;
            }
            if (totalHeight > maxHeight) {
                totalHeight = maxHeight;
            }
        }

        // 应用样式
        $('#frontend-overlay').css({
            top: top,
            left: left,
            height: totalHeight,
        });

        // 自动选择第一项
        $('#frontend-overlay > .dropdown-item').first().addClass('sudo-hover');
    }



    // 插入用户选择的 AI 建议
    function insertSuggestion(text) {
        if (!aiRequested) return; // 只有按了 Tab 才能插入

        quill.insertText(quill.getLength(), " " + text);
        aiAccepted = true;
        document.getElementById("frontend-overlay").classList.add("hidden");
        checkTestCompletion();
    }

    function checkTestCompletion() {
        if (aiRequested && aiAccepted) {
            document.getElementById("status-message").style.display = "block";
            document.getElementById("next-page-btn").style.display = "inline-block";
        }
    }

    document.getElementById("next-page-btn").addEventListener("click", function () {
        window.location.href = "index.html" + currentParams;
    });
});
